### PR TITLE
Add demo notebook using hydrofabric database

### PR DESCRIPTION
**Pull request by jpolchlo**
## Overview

In #110, we loaded the hydrofabric database into our RDS instance.  This PR contributes a Jupyter notebook that makes use of that database.

### Checklist

- [ ] Ran `nbautoexport export .` in `/opt/src/notebooks` and committed the generated scripts. This is to make reviewing notebooks easier. (Note the export will happen automatically after saving notebooks from the Jupyter web app.)
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

### Notes

After experimenting with this data source, it seems clear to me that it is not useful for most applications.  Using the NHD-related classes in `pynhd` (HyRiver) will be far more productive.

### CODE REVIEW

**Comment by jpolchlo** [comment]
Can I get an assist from @vlulla or @rajadain with this `nbautoexport` instruction in the PR template?  I'm not sure what that means.

**Comment by rajadain** [comment]
You can use something like this:

```bash
docker compose run --rm --entrypoint "/bin/bash -c" jupyter "cd notebooks && nbautoexport export ."
```

We should consider adding a script `~/scripts/nbautoexport` that does this.

**Comment by vlulla** [comment]
I'm a little surprised that the script wasn't created automatically! We have already configured this https://github.com/drivendataorg/nbautoexport/#configuring-export-options but it does not seem work.

**Review by rajadain — APPROVED** [review]

**Comment by jpolchlo** [comment]
The nb autoexport stuff seems to be not that important.  Pushing the big green button.

**Pull request merged**
