### PR TITLE
Update shape extraction

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Since PostGIS is now first, before the import, the shapes are no longer stored as bytes in the database, but as hex, needing a different manner of extraction into Shapely.

See https://stackoverflow.com/a/46802086/6995854

### Demo

image

### Notes

For the original discussion see https://azavea.slack.com/archives/C0167LYVB6D/p1655152367266309

### CODE REVIEW

**Comment by vlulla** [comment]
This looks good to me! Should I just "close with comment"?

**Comment by rajadain** [comment]
The classic workflow is to "approve" the PR, and then assign it back to the original author, who then merges it.

**Comment by rajadain** [comment]
If you go to the Files Changed tab, there's a Review Changes button to the right, and from there you can Approve or Request Changes or just leave a comment

**Review by vlulla — COMMENTED** [review]
Looks good!

**Pull request merged**
